version: '3.8'
services:
  app:
    image: vending_machine_app:latest
    restart: always
    volumes:
      - ./:/var/www/html # Mount the entire project for local testing (not for production)
    environment:
      - APP_ENV=local # Use local env for testing
      - APP_DEBUG=true # Enable debug for testing
      - APP_KEY=
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=vending_machine
      - DB_USERNAME=sail
      - DB_PASSWORD=password
    depends_on:
      - database

  web:
    image: vending_machine_web:latest
    restart: always
    ports:
      - "8000:80" # Map host port 8000 to container port 80
    depends_on:
      - app

  database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
      MYSQL_USER: sail
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
