services:
  # The all-in-one Laravel, Nginx, and PHP-FPM container
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "80:80" # Expose port 80 from this container
    volumes:
      - ./.env:/var/www/html/.env # Mount the .env file
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    networks:
      - app-network

  # The MySQL Database
  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: vending_machine
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: vm8834
      MYSQL_ROOT_PASSWORD: vm8834
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

# Docker Networks
networks:
  app-network:
    driver: bridge

# Persistent Volume for Database
volumes:
  db_data:
    driver: local
